jobs:
  - job: Blackduck
    displayName: Blackduck Scan
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            export DETECT_PROJECT_NAME="PipelinePractice"
            export DETECT_PROJECT_VERSION_NAME="In_Development"
            export BLACKDUCK_URL=""
            export BLACKDUCK_API_TOKEN="$(BLACKDUCK_API_TOKEN)"
            export DETECT_BDIO_OUTPUT_PATH="./artifacts"
            export DETECT_DETECTOR_SEARCH_EXCLUSION=""
            export DETECT_INCLUDED_DETECTOR_TYPES="COCOAPODS"
            export DETECT_REPORT_TIMEOUT="3600"
            export DETECT_RISK_REPORT_PDF="true"
            export DETECT_RISK_REPORT_PDF_PATH="./artifacts"
            bash <(curl -s -L https://detect.synopsys.com/detect.sh)